sonar.projectKey=Mian-M-Jahanzaib_cohort-9-mern-14257-mian
sonar.organization=mian-m-jahanzaib

sonar.sources=frontend/src,backend/src

sonar.tests=frontend/src,backend/src/tests
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/tests/**

sonar.exclusions=**/node_modules/**,frontend/dist/**
sonar.sourceEncoding=UTF-8